// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// meanSquaredDistance
NumericVector meanSquaredDistance(NumericVector x, NumericVector y, double mx, double my);
RcppExport SEXP rhrBase_meanSquaredDistance(SEXP xSEXP, SEXP ySEXP, SEXP mxSEXP, SEXP mySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type mx(mxSEXP);
    Rcpp::traits::input_parameter< double >::type my(mySEXP);
    __result = Rcpp::wrap(meanSquaredDistance(x, y, mx, my));
    return __result;
END_RCPP
}
// simpleRandomWalk
List simpleRandomWalk(float sx, float sy, NumericVector sinA, NumericVector cosA, NumericVector d);
RcppExport SEXP rhrBase_simpleRandomWalk(SEXP sxSEXP, SEXP sySEXP, SEXP sinASEXP, SEXP cosASEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< float >::type sx(sxSEXP);
    Rcpp::traits::input_parameter< float >::type sy(sySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sinA(sinASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cosA(cosASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    __result = Rcpp::wrap(simpleRandomWalk(sx, sy, sinA, cosA, d));
    return __result;
END_RCPP
}
