# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

t2cpp3 <- function(t, interval) {
    .Call('rhrBase_t2cpp3', PACKAGE = 'rhrBase', t, interval)
}

binnedCV <- function(xs, ys, freq, hs) {
    .Call('rhrBase_binnedCV', PACKAGE = 'rhrBase', xs, ys, freq, hs)
}

unbinnedCV <- function(xs, ys, hs) {
    .Call('rhrBase_unbinnedCV', PACKAGE = 'rhrBase', xs, ys, hs)
}

meanSquaredDistance <- function(x, y, mx, my) {
    .Call('rhrBase_meanSquaredDistance', PACKAGE = 'rhrBase', x, y, mx, my)
}

simpleRandomWalk <- function(sx, sy, sinA, cosA, d) {
    .Call('rhrBase_simpleRandomWalk', PACKAGE = 'rhrBase', sx, sy, sinA, cosA, d)
}

