# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

meanSquaredDistance <- function(x, y, mx, my) {
    .Call('rhrBase_meanSquaredDistance', PACKAGE = 'rhrBase', x, y, mx, my)
}

simpleRandomWalk <- function(sx, sy, sinA, cosA, d) {
    .Call('rhrBase_simpleRandomWalk', PACKAGE = 'rhrBase', sx, sy, sinA, cosA, d)
}

